repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  # General
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-added-large-files
  # Data formats
  - id: check-toml
  # Python
  - id: check-ast
  - id: check-docstring-first

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-toml
    args: ["--autofix", "--no-sort"]

- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.22
  hooks:
    - id: validate-pyproject

- repo: https://github.com/hhatto/autopep8
  rev: v2.3.1
  hooks:
  - id: autopep8
    args: ["-i", "-aaa", "--max-line-length", "120"]

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    name: sort python imports
    args: ["--multi-line", "3"]

- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
  hooks:
  - id: docformatter
    name: format python docstrings
    args: [--in-place]

- repo: local
  hooks:
  - id: python-coverage
    name: check test coverage
    entry: bash -c "coverage run tests.py && coverage report -m --skip-covered"
    language: python
    additional_dependencies: ["coverage"]
    types: [python]
    verbose: true
    pass_filenames: false
