repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  # General
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-added-large-files
  # Data formats
  - id: check-toml
  # Python
  - id: check-ast
  - id: check-docstring-first

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.10.0
  hooks:
  - id: pretty-format-toml
    args: ["--autofix", "--no-sort"]

- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.14
  hooks:
    - id: validate-pyproject

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.0
  hooks:
  - id: autopep8
    args: ["-i", "-aaa", "--max-line-length", "120"]

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: sort python imports
    args: ["--multi-line", "3"]

- repo: https://github.com/PyCQA/docformatter
  rev: v1.5.0
  hooks:
  - id: docformatter
    name: format python docstrings
    args: [--in-place]

- repo: local
  hooks:
  - id: python-unittest
    name: run python tests
    entry: python -m unittest
    language: python
    types: [python]
    pass_filenames: false
