name: "Coverage"

on:
  push:
    branches: [ "main" ]
    paths: [ "*.py" ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage genbadge[coverage]
    - name: Set up pages directories
      run: |
        mkdir pages
        mkdir pages/badges
    - name: Collect coverage results
      run: |
        coverage run -m unittest
        coverage html -d pages/coverage
        coverage xml -o coverage.xml
    - name: Create badge
      run: |
        genbadge coverage -i coverage.xml -o pages/badges/coverage.svg
    - name: Publish coverage report to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: pages/coverage
        target-folder: coverage
        branch: gh-pages
    - name: Publish coverage badge to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: pages/badges
        target-folder: badges
        clean: false
        branch: gh-pages
